# Dependencies
gems:             [jekyll-paginate]
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            JBaptiste Reynaud
tagline:          'Php dev'
description:      'My personnal blog talking things I found on the web.'
url:              jibe84.github.io
baseurl:          /

author:
  name:           'Jean-Baptiste Reynaud'
  url:            https://twitter.com/jibe_84

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/jibe84
