# Dependencies
gems:             [jekyll-paginate]
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            JBaptiste Reynaud
tagline:          'A Jekyll theme'
description:      'A brazeen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Jean-Baptiste Reynaud'
  url:            https://twitter.com/jibe_84

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/jibe84
