# Dependencies
gems:             [jekyll-paginate]
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            JBaptiste Reynaud
tagline:          'Php dev'
description:      'My personnal blog talking about things I found on the web. My twitter <a href="https://twitter.com/jibe_84" target="_blank">@jibe_84</a>'
url:              jibe84.github.io
baseurl:          /

author:
  name:           'Jean-Baptiste Reynaud'
  url:            https://twitter.com/jibe_84

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/jibe84
